import pygame
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60
ENEMY_NUMBERS = 4
ENEMY_TYPES = ("knight", "goblin", "purple_goblin", "red_goblin")
ENEMY_HEALTHS = (100, 150, 175, 200)
ENEMY_SPEEDS = (1, 2, 3, 4)
clock = pygame.time.Clock()
armour = pygame.image.load("assets/armour.png")
bg = pygame.image.load("assets/bg.png")
bullet = pygame.image.load("assets/bullet.png")
crosshair = pygame.image.load("assets/crosshair.png")
repair = pygame.image.load("assets/repair.png")
castle_25 = pygame.image.load("assets/castle/castle_25.png")
castle_50 = pygame.image.load("assets/castle/castle_50.png")
castle_100 = pygame.image.load("assets/castle/castle_100.png")
tower_25 = pygame.image.load("assets/tower/tower_25.png")
tower_50 = pygame.image.load("assets/tower/tower_50.png")
tower_100 = pygame.image.load("assets/tower/tower_100.png")